version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Kasia12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - spring-boot-network

networks:
  spring-boot-network:
    driver: bridge